# Generated by Django 6.0.6 on 2026-07-13 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=50)),
                ('year_reference', models.IntegerField()),
                ('course_name', models.CharField(max_length=200)),
                ('campus', models.CharField(max_length=100)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('shift', models.CharField(max_length=50)),
                ('total_spots_filled', models.IntegerField(default=0)),
                ('leftover_spots', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCandidatoDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escola_publica', models.BooleanField(default=True, verbose_name='Estudou em Escola Pública?')),
                ('renda_sm', models.FloatField(default=1.0, verbose_name='Renda Familiar (em Salários Mínimos por pessoa na residência)')),
                ('raca', models.CharField(choices=[('branca', 'Branca'), ('preta', 'Preta'), ('parda', 'Parda'), ('indigena', 'Indígena'), ('quilombola', 'Quilombola')], default='branca', max_length=20, verbose_name='Raça/Cor')),
                ('pcd', models.BooleanField(default=False, verbose_name='Pessoa com Deficiência (PCD)?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_candidato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('spots', models.IntegerField(default=0)),
                ('previous_cutoff', models.FloatField(blank=True, null=True)),
                ('historical_max_score', models.FloatField(blank=True, null=True)),
                ('institution', models.CharField(blank=True, default='', help_text='Desnormalizado de course_offering.institution para facilitar filtros diretos.', max_length=50, verbose_name='Instituição')),
                ('is_ampla_concorrencia', models.BooleanField(default=False, help_text='AC (UFPA/IFPA/UFRA) ou A (UEPA). Aberta a todos.', verbose_name='Ampla Concorrência')),
                ('requer_escola_publica', models.BooleanField(default=False, help_text='Exige que o candidato tenha cursado o ensino médio integralmente em escola pública.', verbose_name='Requer Escola Pública')),
                ('requer_renda_baixa', models.BooleanField(default=False, help_text='Exige renda familiar per capita igual ou inferior a 1 salário mínimo.', verbose_name='Requer Renda Baixa (≤ 1 SM)')),
                ('is_pcd', models.BooleanField(default=False, help_text='Vaga reservada para Pessoas com Deficiência.', verbose_name='Para PcD')),
                ('is_adicional_pcd', models.BooleanField(default=False, help_text='Cota adicional exclusiva para PcD independente de escola pública (UFPA: PCDA / UEPA: B).', verbose_name='Cota Adicional PcD')),
                ('is_ppi', models.BooleanField(default=False, help_text='Vaga reservada para autodeclarados Pretos, Pardos ou Indígenas.', verbose_name='Para PPI')),
                ('is_quilombola', models.BooleanField(default=False, help_text='Vaga reservada para autodeclarados Quilombolas.', verbose_name='Para Quilombola')),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='notas.courseoffering')),
            ],
        ),
    ]
